openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for Assets
paths:
    /api/diagrams:
        post:
            tags:
                - SVG
            summary: Save SVG
            description: Save the SVG streamed in the request body
            operationId: SVG#Save
            parameters:
                - name: file
                  in: query
                  description: Diagram SVG filename
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Diagram SVG filename
                    example: diagram.svg
                    pattern: .*\.svg
                  example: diagram.svg
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SaveRequestBody'
                        example:
                            SVG: <svg����</svg>
            responses:
                "204":
                    description: No Content response.
    /api/diagrams/layout:
        get:
            tags:
                - SVG
            summary: Load SVG
            description: Stream the model layout JSON saved in the SVG
            operationId: SVG#Load
            parameters:
                - name: file
                  in: query
                  description: Diagram SVG filename
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Diagram SVG filename
                    example: diagram.svg
                    pattern: .*\.svg
                  example: diagram.svg
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: <svg���</svg>
                                pattern: <svg.*</svg>$
                            example: <svg���</svg>
    /api/dsl:
        post:
            tags:
                - DSLEditor
            summary: UpdateDSL DSLEditor
            description: Update the DSL for the given package, compile it and return the corresponding JSON if successful
            operationId: DSLEditor#UpdateDSL
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateDSLRequestBody'
                        example:
                            Content: |-
                                import . "goa.design/model/dsl"

                                var _ = Design(func() {})
                            Locator:
                                Dir: src/repo/model
                                Filename: model.go
                                Workspace: my-workspace
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/dsl/component:
        put:
            tags:
                - DSLEditor
            summary: UpsertComponent DSLEditor
            description: Create or update a component in the model
            operationId: DSLEditor#UpsertComponent
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertComponentRequestBody'
                        example:
                            ContainerName: My Container
                            Description: Component description
                            Locator:
                                Dir: src/repo/model
                                Filename: model.go
                                Workspace: my-workspace
                            Name: Component
                            Properties:
                                key1: value1
                                key2: value2
                            SystemName: My System
                            Tags:
                                - Tag1
                                - Tag2
                            Technology: Technology
                            URL: https://component.com
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/dsl/container:
        put:
            tags:
                - DSLEditor
            summary: UpsertContainer DSLEditor
            description: Create or update a container in the model
            operationId: DSLEditor#UpsertContainer
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertContainerRequestBody'
                        example:
                            Description: Container description
                            Locator:
                                Dir: src/repo/model
                                Filename: model.go
                                Workspace: my-workspace
                            Name: Container
                            Properties:
                                key1: value1
                                key2: value2
                            SystemName: My System
                            Tags:
                                - Tag1
                                - Tag2
                            Technology: Technology
                            URL: https://container.com
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/dsl/person:
        put:
            tags:
                - DSLEditor
            summary: UpsertPerson DSLEditor
            description: Create or update a person in the model
            operationId: DSLEditor#UpsertPerson
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertSystemRequestBody'
                        example:
                            Description: Person description
                            Location: Internal
                            Locator:
                                Dir: src/repo/model
                                Filename: model.go
                                Workspace: my-workspace
                            Name: Person
                            Properties:
                                key1: value1
                                key2: value2
                            Tags:
                                - Tag1
                                - Tag2
                            URL: https://person.com
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/dsl/person/{PersonName}:
        delete:
            tags:
                - DSLEditor
            summary: DeletePerson DSLEditor
            description: Delete an existing person from the model
            operationId: DSLEditor#DeletePerson
            parameters:
                - name: PersonName
                  in: path
                  description: Name of person to delete
                  required: true
                  schema:
                    type: string
                    description: Name of person to delete
                    example: Nesciunt fugiat laborum.
                  example: Et in.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FileLocator'
                        example:
                            Dir: src/repo/model
                            Filename: model.go
                            Workspace: my-workspace
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Person not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/dsl/relationship:
        delete:
            tags:
                - DSLEditor
            summary: DeleteRelationship DSLEditor
            description: Delete an existing relationship from the model
            operationId: DSLEditor#DeleteRelationship
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteRelationshipRequestBody'
                        example:
                            DestinationPath: Software System/Container/Component
                            Dir: src/repo/model
                            Filename: model.go
                            SourcePath: Software System/Container/Component
                            Workspace: my-workspace
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Relationship not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        put:
            tags:
                - DSLEditor
            summary: UpsertRelationship DSLEditor
            description: Create or update a relationship in the model
            operationId: DSLEditor#UpsertRelationship
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertRelationshipRequestBody'
                        example:
                            Description: Relationship description
                            DestinationPath: Software System/Container/Component
                            InteractionStyle: Asynchronous
                            Locator:
                                Dir: src/repo/model
                                Filename: model.go
                                Workspace: my-workspace
                            SourcePath: Software System/Container/Component
                            Tags:
                                - Tag1
                                - Tag2
                            Technology: Technology
                            URL: https://relationship.com
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/dsl/system:
        put:
            tags:
                - DSLEditor
            summary: UpsertSystem DSLEditor
            description: Create or update a software system in the model
            operationId: DSLEditor#UpsertSystem
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertSystemRequestBody'
                        example:
                            Description: System description
                            Location: Internal
                            Locator:
                                Dir: src/repo/model
                                Filename: model.go
                                Workspace: my-workspace
                            Name: System
                            Properties:
                                key1: value1
                                key2: value2
                            Tags:
                                - Tag1
                                - Tag2
                            URL: https://system.com
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/dsl/system/{SystemName}:
        delete:
            tags:
                - DSLEditor
            summary: DeleteSystem DSLEditor
            description: Delete an existing software system from the model
            operationId: DSLEditor#DeleteSystem
            parameters:
                - name: SystemName
                  in: path
                  description: Name of software system to delete
                  required: true
                  schema:
                    type: string
                    description: Name of software system to delete
                    example: Consequatur ullam et temporibus non in.
                  example: Inventore molestiae.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FileLocator'
                        example:
                            Dir: src/repo/model
                            Filename: model.go
                            Workspace: my-workspace
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Software system not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/dsl/system/{SystemName}/container/{ContainerName}:
        delete:
            tags:
                - DSLEditor
            summary: DeleteContainer DSLEditor
            description: Delete an existing container from the model
            operationId: DSLEditor#DeleteContainer
            parameters:
                - name: SystemName
                  in: path
                  description: Name of container software system
                  required: true
                  schema:
                    type: string
                    description: Name of container software system
                    example: Consequatur dolorem voluptatem labore.
                  example: Odit id odit sit quos quia ut.
                - name: ContainerName
                  in: path
                  description: Name of container to delete
                  required: true
                  schema:
                    type: string
                    description: Name of container to delete
                    example: Nostrum accusamus aspernatur facere dolorem velit.
                  example: Cupiditate et dolore inventore.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FileLocator'
                        example:
                            Dir: src/repo/model
                            Filename: model.go
                            Workspace: my-workspace
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Container not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/dsl/system/{SystemName}/container/{ContainerName}/component/{ComponentName}:
        delete:
            tags:
                - DSLEditor
            summary: DeleteComponent DSLEditor
            description: Delete an existing component from the model
            operationId: DSLEditor#DeleteComponent
            parameters:
                - name: SystemName
                  in: path
                  description: Name of component software system
                  required: true
                  schema:
                    type: string
                    description: Name of component software system
                    example: My System
                  example: My System
                - name: ContainerName
                  in: path
                  description: Name of component software system
                  required: true
                  schema:
                    type: string
                    description: Name of component software system
                    example: My Container
                  example: My Container
                - name: ComponentName
                  in: path
                  description: Name of component to delete
                  required: true
                  schema:
                    type: string
                    description: Name of component to delete
                    example: My Component
                  example: My Component
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FileLocator'
                        example:
                            Dir: src/repo/model
                            Filename: model.go
                            Workspace: my-workspace
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Component not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/packages:
        delete:
            tags:
                - Packages
            summary: DeletePackage Packages
            description: Delete the given model package
            operationId: Packages#DeletePackage
            parameters:
                - name: work
                  in: query
                  description: Workspace identifier
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Workspace identifier
                    example: my-workspace
                    minLength: 1
                  example: my-workspace
                - name: dir
                  in: query
                  description: Path to directory containing a model package
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Path to directory containing a model package
                    example: src/repo/model
                    minLength: 1
                  example: src/repo/model
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: Package not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        get:
            tags:
                - Packages
            summary: ListPackages Packages
            description: List the model packages in the given workspace
            operationId: Packages#ListPackages
            parameters:
                - name: work
                  in: query
                  description: Workspace identifier
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Workspace identifier
                    example: my-workspace
                    minLength: 1
                  example: my-workspace
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Package'
                                example:
                                    - Dir: src/repo/model
                                      ImportPath: goa.design/model/examples/basic/model
                                    - Dir: src/repo/model
                                      ImportPath: goa.design/model/examples/basic/model
                            example:
                                - Dir: src/repo/model
                                  ImportPath: goa.design/model/examples/basic/model
                                - Dir: src/repo/model
                                  ImportPath: goa.design/model/examples/basic/model
                                - Dir: src/repo/model
                                  ImportPath: goa.design/model/examples/basic/model
        post:
            tags:
                - Packages
            summary: CreatePackage Packages
            description: Create a new model package in the given workspace
            operationId: Packages#CreatePackage
            parameters:
                - name: work
                  in: query
                  description: Workspace identifier
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Workspace identifier
                    example: my-workspace
                    minLength: 1
                  example: my-workspace
                - name: dir
                  in: query
                  description: Path to directory containing a model package
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Path to directory containing a model package
                    example: src/repo/model
                    minLength: 1
                  example: src/repo/model
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreatePackageRequestBody'
                        example:
                            Content: |-
                                import . "goa.design/model/dsl"

                                var _ = Design("System Design", func() {

                                })
            responses:
                "201":
                    description: Created response.
                "409":
                    description: 'already_exists: Package already exists'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/packages/files:
        get:
            tags:
                - Packages
            summary: ReadPackageFiles Packages
            description: Get the DSL files and their content for the given model package
            operationId: Packages#ReadPackageFiles
            parameters:
                - name: work
                  in: query
                  description: Workspace identifier
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Workspace identifier
                    example: my-workspace
                    minLength: 1
                  example: my-workspace
                - name: dir
                  in: query
                  description: Path to directory containing a model package
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Path to directory containing a model package
                    example: src/repo/model
                    minLength: 1
                  example: src/repo/model
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/UpdateDSLRequestBody'
                                example:
                                    - Content: |-
                                        import . "goa.design/model/dsl"

                                        var _ = Design(func() {})
                                      Locator:
                                        Dir: src/repo/model
                                        Filename: model.go
                                        Workspace: my-workspace
                                    - Content: |-
                                        import . "goa.design/model/dsl"

                                        var _ = Design(func() {})
                                      Locator:
                                        Dir: src/repo/model
                                        Filename: model.go
                                        Workspace: my-workspace
                                    - Content: |-
                                        import . "goa.design/model/dsl"

                                        var _ = Design(func() {})
                                      Locator:
                                        Dir: src/repo/model
                                        Filename: model.go
                                        Workspace: my-workspace
                            example:
                                - Content: |-
                                    import . "goa.design/model/dsl"

                                    var _ = Design(func() {})
                                  Locator:
                                    Dir: src/repo/model
                                    Filename: model.go
                                    Workspace: my-workspace
                                - Content: |-
                                    import . "goa.design/model/dsl"

                                    var _ = Design(func() {})
                                  Locator:
                                    Dir: src/repo/model
                                    Filename: model.go
                                    Workspace: my-workspace
                                - Content: |-
                                    import . "goa.design/model/dsl"

                                    var _ = Design(func() {})
                                  Locator:
                                    Dir: src/repo/model
                                    Filename: model.go
                                    Workspace: my-workspace
                                - Content: |-
                                    import . "goa.design/model/dsl"

                                    var _ = Design(func() {})
                                  Locator:
                                    Dir: src/repo/model
                                    Filename: model.go
                                    Workspace: my-workspace
    /api/packages/subscribe:
        get:
            tags:
                - Packages
            summary: Subscribe Packages
            description: Send model JSON on initial subscription and when the model package changes
            operationId: Packages#Subscribe
            parameters:
                - name: work
                  in: query
                  description: Workspace identifier
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Workspace identifier
                    example: my-workspace
                    minLength: 1
                  example: my-workspace
                - name: dir
                  in: query
                  description: Path to directory containing a model package
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Path to directory containing a model package
                    example: src/repo/model
                    minLength: 1
                  example: src/repo/model
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: '{"name":"example","email":"mail@example.com"}'
                                format: json
                            example: '{"name":"example","email":"mail@example.com"}'
    /api/packages/workspaces:
        get:
            tags:
                - Packages
            summary: ListWorkspaces Packages
            description: List the known workspaces
            operationId: Packages#ListWorkspaces
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Workspace'
                                example:
                                    - Workspace: my-workspace
                                    - Workspace: my-workspace
                                    - Workspace: my-workspace
                            example:
                                - Workspace: my-workspace
                                - Workspace: my-workspace
                                - Workspace: my-workspace
    /assets:
        get:
            tags:
                - Assets
            summary: Download assets
            description: Serve the diagram editor UI
            operationId: Assets#/assets
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreatePackageRequestBody:
            type: object
            properties:
                Content:
                    type: string
                    description: DSL code
                    example: |-
                        import . "goa.design/model/dsl"

                        var _ = Design("System Design", func() {

                        })
                    pattern: import . "goa.design/model/dsl"
                    minLength: 58
            example:
                Content: |-
                    import . "goa.design/model/dsl"

                    var _ = Design("System Design", func() {

                    })
            required:
                - Content
        DeleteRelationshipRequestBody:
            type: object
            properties:
                DestinationPath:
                    type: string
                    description: Path to destination element, see SourcePath for details.
                    example: Software System/Container/Component
                Dir:
                    type: string
                    description: Path to directory containing a model package
                    example: src/repo/model
                    minLength: 1
                Filename:
                    type: string
                    description: Name of DSL file
                    example: model.go
                    pattern: \.go$
                SourcePath:
                    type: string
                    description: Path to source element consisting of <software system name>[/<container name>[/<component name>]]
                    example: Software System/Container/Component
                Workspace:
                    type: string
                    description: Workspace identifier
                    example: my-workspace
                    minLength: 1
            example:
                DestinationPath: Software System/Container/Component
                Dir: src/repo/model
                Filename: model.go
                SourcePath: Software System/Container/Component
                Workspace: my-workspace
            required:
                - SourcePath
                - DestinationPath
                - Filename
                - Workspace
                - Dir
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            description: Compilation failed
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        FileLocator:
            type: object
            properties:
                Dir:
                    type: string
                    description: Path to directory containing a model package
                    example: src/repo/model
                    minLength: 1
                Filename:
                    type: string
                    description: Name of DSL file
                    example: model.go
                    pattern: \.go$
                Workspace:
                    type: string
                    description: Workspace identifier
                    example: my-workspace
                    minLength: 1
            description: FileLocator is the location of a DSL file in a model package
            example:
                Dir: src/repo/model
                Filename: model.go
                Workspace: my-workspace
            required:
                - Filename
                - Workspace
                - Dir
        Package:
            type: object
            properties:
                Dir:
                    type: string
                    description: Path to directory containing a model package
                    example: src/repo/model
                    minLength: 1
                ImportPath:
                    type: string
                    description: Design Go package import path
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
            example:
                Dir: src/repo/model
                ImportPath: goa.design/model/examples/basic/model
            required:
                - ImportPath
                - Dir
        SaveRequestBody:
            type: object
            properties:
                SVG:
                    type: string
                    description: Diagram SVG
                    example: <svg���</svg>
                    pattern: <svg.*</svg>$
            example:
                SVG: <svg����</svg>
            required:
                - SVG
        UpdateDSLRequestBody:
            type: object
            properties:
                Content:
                    type: string
                    description: DSL code
                    example: |-
                        import . "goa.design/model/dsl"

                        var _ = Design(func() {})
                    pattern: import . "goa.design/model/dsl"
                    minLength: 58
                Locator:
                    $ref: '#/components/schemas/FileLocator'
            example:
                Content: |-
                    import . "goa.design/model/dsl"

                    var _ = Design(func() {})
                Locator:
                    Dir: src/repo/model
                    Filename: model.go
                    Workspace: my-workspace
            required:
                - Locator
                - Content
        UpsertComponentRequestBody:
            type: object
            properties:
                ContainerName:
                    type: string
                    description: Name of parent container
                    example: My Container
                Description:
                    type: string
                    description: Description of component
                    example: Component description
                Locator:
                    $ref: '#/components/schemas/FileLocator'
                Name:
                    type: string
                    description: Name of component
                    example: Component
                Properties:
                    type: object
                    description: Set of arbitrary name-value properties (shown in diagram tooltips)
                    example:
                        key1: value1
                        key2: value2
                    additionalProperties:
                        type: string
                        example: Voluptas magni ad.
                SystemName:
                    type: string
                    description: Name of parent software system
                    example: My System
                Tags:
                    type: array
                    items:
                        type: string
                        example: Quas quis ratione provident.
                    description: Attached tags
                    example:
                        - Tag1
                        - Tag2
                Technology:
                    type: string
                    description: Technology used by component
                    example: Technology
                URL:
                    type: string
                    description: Documentation URL
                    example: https://component.com
            example:
                ContainerName: My Container
                Description: Component description
                Locator:
                    Dir: src/repo/model
                    Filename: model.go
                    Workspace: my-workspace
                Name: Component
                Properties:
                    key1: value1
                    key2: value2
                SystemName: My System
                Tags:
                    - Tag1
                    - Tag2
                Technology: Technology
                URL: https://component.com
            required:
                - SystemName
                - ContainerName
                - Name
        UpsertContainerRequestBody:
            type: object
            properties:
                Description:
                    type: string
                    description: Description of container
                    example: Container description
                Locator:
                    $ref: '#/components/schemas/FileLocator'
                Name:
                    type: string
                    description: Name of container
                    example: Container
                Properties:
                    type: object
                    description: Set of arbitrary name-value properties (shown in diagram tooltips)
                    example:
                        key1: value1
                        key2: value2
                    additionalProperties:
                        type: string
                        example: Libero accusamus.
                SystemName:
                    type: string
                    description: Name of parent software system
                    example: My System
                Tags:
                    type: array
                    items:
                        type: string
                        example: Et perspiciatis delectus illo distinctio impedit.
                    description: Attached tags
                    example:
                        - Tag1
                        - Tag2
                Technology:
                    type: string
                    description: Technology used by container
                    example: Technology
                URL:
                    type: string
                    description: Documentation URL
                    example: https://container.com
            example:
                Description: Container description
                Locator:
                    Dir: src/repo/model
                    Filename: model.go
                    Workspace: my-workspace
                Name: Container
                Properties:
                    key1: value1
                    key2: value2
                SystemName: My System
                Tags:
                    - Tag1
                    - Tag2
                Technology: Technology
                URL: https://container.com
            required:
                - SystemName
                - Name
        UpsertRelationshipRequestBody:
            type: object
            properties:
                Description:
                    type: string
                    description: Description of relationship
                    example: Relationship description
                DestinationPath:
                    type: string
                    description: Path to destination element, see SourcePath for details.
                    example: Software System/Container/Component
                InteractionStyle:
                    type: string
                    description: Indicates whether the relationship is synchronous or asynchronous
                    default: Synchronous
                    example: Synchronous
                    enum:
                        - Synchronous
                        - Asynchronous
                Locator:
                    $ref: '#/components/schemas/FileLocator'
                SourcePath:
                    type: string
                    description: Path to source element consisting of <software system name>[/<container name>[/<component name>]]
                    example: Software System/Container/Component
                Tags:
                    type: array
                    items:
                        type: string
                        example: Amet minus velit non omnis earum amet.
                    description: Attached tags
                    example:
                        - Tag1
                        - Tag2
                Technology:
                    type: string
                    description: Technology used by relationship
                    example: Technology
                URL:
                    type: string
                    description: Documentation URL
                    example: https://relationship.com
                    format: uri
            example:
                Description: Relationship description
                DestinationPath: Software System/Container/Component
                InteractionStyle: Synchronous
                Locator:
                    Dir: src/repo/model
                    Filename: model.go
                    Workspace: my-workspace
                SourcePath: Software System/Container/Component
                Tags:
                    - Tag1
                    - Tag2
                Technology: Technology
                URL: https://relationship.com
            required:
                - SourcePath
                - DestinationPath
        UpsertSystemRequestBody:
            type: object
            properties:
                Description:
                    type: string
                    description: Description of system
                    example: System description
                Location:
                    type: string
                    description: Indicates whether the system is in-house (Internal) or hosted by a third party (External)
                    default: Internal
                    example: Internal
                    enum:
                        - Internal
                        - External
                Locator:
                    $ref: '#/components/schemas/FileLocator'
                Name:
                    type: string
                    description: Name of software system
                    example: System
                Properties:
                    type: object
                    description: Set of arbitrary name-value properties (shown in diagram tooltips)
                    example:
                        key1: value1
                        key2: value2
                    additionalProperties:
                        type: string
                        example: Ut magnam ut voluptates ipsam ut.
                Tags:
                    type: array
                    items:
                        type: string
                        example: Dolorem accusamus nam iste.
                    description: Attached tags
                    example:
                        - Tag1
                        - Tag2
                URL:
                    type: string
                    description: Documentation URL
                    example: https://system.com
            example:
                Description: System description
                Location: External
                Locator:
                    Dir: src/repo/model
                    Filename: model.go
                    Workspace: my-workspace
                Name: System
                Properties:
                    key1: value1
                    key2: value2
                Tags:
                    - Tag1
                    - Tag2
                URL: https://system.com
            required:
                - Name
        Workspace:
            type: object
            properties:
                Workspace:
                    type: string
                    description: Workspace identifier
                    example: my-workspace
                    minLength: 1
            example:
                Workspace: my-workspace
            required:
                - Workspace
tags:
    - name: Assets
    - name: DSLEditor
    - name: Packages
    - name: SVG
