openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for Editor
paths:
    /api/editor/component:
        put:
            tags:
                - Editor
            summary: UpsertComponent Editor
            description: Create or update a component in the model
            operationId: Editor#UpsertComponent
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertComponentRequestBody'
                        example:
                            ContainerName: My Container
                            Description: Component description
                            Name: Component
                            Properties:
                                key1: value1
                                key2: value2
                            SystemName: My System
                            Tags:
                                - Tag1
                                - Tag2
                            Technology: Technology
                            URL: https://component.com
            responses:
                "204":
                    description: No Content response.
    /api/editor/container:
        put:
            tags:
                - Editor
            summary: UpsertContainer Editor
            description: Create or update a container in the model
            operationId: Editor#UpsertContainer
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertContainerRequestBody'
                        example:
                            Description: Container description
                            Name: Container
                            Properties:
                                key1: value1
                                key2: value2
                            SystemName: My System
                            Tags:
                                - Tag1
                                - Tag2
                            Technology: Technology
                            URL: https://container.com
            responses:
                "204":
                    description: No Content response.
    /api/editor/person:
        put:
            tags:
                - Editor
            summary: UpsertPerson Editor
            description: Create or update a person in the model
            operationId: Editor#UpsertPerson
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertSystemRequestBody'
                        example:
                            Description: Person description
                            Location: Internal
                            Name: Person
                            Properties:
                                key1: value1
                                key2: value2
                            Tags:
                                - Tag1
                                - Tag2
                            URL: https://person.com
            responses:
                "204":
                    description: No Content response.
    /api/editor/person/{Name}:
        delete:
            tags:
                - Editor
            summary: DeletePerson Editor
            description: Delete an existing person from the model
            operationId: Editor#DeletePerson
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
                - name: Name
                  in: path
                  description: Name of person to delete
                  required: true
                  schema:
                    type: string
                    description: Name of person to delete
                    example: Distinctio omnis occaecati ex sed sed.
                  example: Rerum magnam.
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'NotFound: Person not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/editor/relationship:
        put:
            tags:
                - Editor
            summary: UpsertRelationship Editor
            description: Create or update a relationship in the model
            operationId: Editor#UpsertRelationship
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertRelationshipRequestBody'
                        example:
                            Description: Relationship description
                            DestinationPath: Software System/Container/Component
                            InteractionStyle: Synchronous
                            SourcePath: Software System/Container/Component
                            Tags:
                                - Tag1
                                - Tag2
                            Technology: Technology
                            URL: https://relationship.com
            responses:
                "204":
                    description: No Content response.
    /api/editor/relationship/{SourcePath}/{DestinationPath}:
        delete:
            tags:
                - Editor
            summary: DeleteRelationship Editor
            description: Delete an existing relationship from the model
            operationId: Editor#DeleteRelationship
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
                - name: SourcePath
                  in: path
                  description: Path to source element consisting of <software system name>[/<container name>[/<component name>]]
                  required: true
                  schema:
                    type: string
                    description: Path to source element consisting of <software system name>[/<container name>[/<component name>]]
                    example: Software System/Container/Component
                  examples:
                    Component:
                        summary: Component
                        value: Software System/Container/Component
                    Container:
                        summary: Container
                        value: Software System/Container
                    Software System:
                        summary: Software System
                        value: Software System
                - name: DestinationPath
                  in: path
                  description: Path to destination element, see SourcePath for details.
                  required: true
                  schema:
                    type: string
                    description: Path to destination element, see SourcePath for details.
                    example: Software System/Container/Component
                  examples:
                    Component:
                        summary: Component
                        value: Software System/Container/Component
                    Container:
                        summary: Container
                        value: Software System/Container
                    Software System:
                        summary: Software System
                        value: Software System
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'NotFound: Relationship not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/editor/system:
        put:
            tags:
                - Editor
            summary: UpsertSystem Editor
            description: Create or update a software system in the model
            operationId: Editor#UpsertSystem
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpsertSystemRequestBody'
                        example:
                            Description: System description
                            Location: External
                            Name: System
                            Properties:
                                key1: value1
                                key2: value2
                            Tags:
                                - Tag1
                                - Tag2
                            URL: https://system.com
            responses:
                "204":
                    description: No Content response.
    /api/editor/system/{Name}:
        delete:
            tags:
                - Editor
            summary: DeleteSystem Editor
            description: Delete an existing software system from the model
            operationId: Editor#DeleteSystem
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
                - name: Name
                  in: path
                  description: Name of software system to delete
                  required: true
                  schema:
                    type: string
                    description: Name of software system to delete
                    example: Animi enim vel eum ipsam.
                  example: Ex et tempore beatae.
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'NotFound: Software system not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/editor/system/{SystemName}/container/{ContainerName}/component/{Name}:
        delete:
            tags:
                - Editor
            summary: DeleteComponent Editor
            description: Delete an existing component from the model
            operationId: Editor#DeleteComponent
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
                - name: SystemName
                  in: path
                  description: Name of component software system
                  required: true
                  schema:
                    type: string
                    description: Name of component software system
                    example: My System
                  example: My System
                - name: ContainerName
                  in: path
                  description: Name of component software system
                  required: true
                  schema:
                    type: string
                    description: Name of component software system
                    example: My Container
                  example: My Container
                - name: Name
                  in: path
                  description: Name of component to delete
                  required: true
                  schema:
                    type: string
                    description: Name of component to delete
                    example: My Component
                  example: My Component
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'NotFound: Component not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/editor/system/{SystemName}/container/{Name}:
        delete:
            tags:
                - Editor
            summary: DeleteContainer Editor
            description: Delete an existing container from the model
            operationId: Editor#DeleteContainer
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
                - name: SystemName
                  in: path
                  description: Name of container software system
                  required: true
                  schema:
                    type: string
                    description: Name of container software system
                    example: Cupiditate voluptatibus.
                  example: Maiores sunt aut velit deserunt delectus.
                - name: Name
                  in: path
                  description: Name of container to delete
                  required: true
                  schema:
                    type: string
                    description: Name of container to delete
                    example: Voluptas dolores eligendi aperiam vitae.
                  example: Sit consequuntur in voluptatem nihil hic ad.
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'NotFound: Container not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/modules:
        get:
            tags:
                - Module
            summary: ListModules Module
            description: List the model modules in the current Go workspace
            operationId: Module#ListModules
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Module'
                                example:
                                    - GoMod: goa.design/model/examples/basic/model
                                    - GoMod: goa.design/model/examples/basic/model
                                    - GoMod: goa.design/model/examples/basic/model
                                    - GoMod: goa.design/model/examples/basic/model
                            example:
                                - GoMod: goa.design/model/examples/basic/model
                                - GoMod: goa.design/model/examples/basic/model
                                - GoMod: goa.design/model/examples/basic/model
    /api/modules/compile:
        post:
            tags:
                - Module
            summary: Compile Module
            description: Stream the model DSL, save it, compile it and return the corresponding JSON
            operationId: Module#Compile
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: '{"name":"example","email":"mail@example.com"}'
                                format: json
                            example: '{"name":"example","email":"mail@example.com"}'
                "400":
                    description: 'compilation_failed: Compilation failed'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/modules/diagram:
        post:
            tags:
                - Module
            summary: WriteDiagram Module
            description: Save the SVG streamed in the request body
            operationId: Module#WriteDiagram
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            responses:
                "204":
                    description: No Content response.
    /api/modules/layout:
        get:
            tags:
                - Module
            summary: GetLayout Module
            description: Stream the model layout JSON saved in the SVG
            operationId: Module#GetLayout
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                format: binary
    /api/modules/model:
        get:
            tags:
                - Module
            summary: GetModel Module
            description: Stream the model JSON, see https://pkg.go.dev/goa.design/model/mdl#Model
            operationId: Module#GetModel
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                format: binary
    /api/modules/subscribe:
        get:
            tags:
                - Module
            summary: Subscribe Module
            description: WebSocket endpoint for subscribing to updates to the model
            operationId: Module#Subscribe
            parameters:
                - name: mod
                  in: query
                  description: Design Go module
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
                  example: goa.design/model/examples/basic/model
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: '{"name":"example","email":"mail@example.com"}'
                                format: json
                            example: '{"name":"example","email":"mail@example.com"}'
    /assets:
        get:
            tags:
                - Assets
            summary: Download assets
            description: Serve the diagram editor UI
            operationId: Assets#/assets
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Software system not found
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        Module:
            type: object
            properties:
                GoMod:
                    type: string
                    description: Design Go module
                    example: goa.design/model/examples/basic/model
                    pattern: ^([a-zA-Z0-9]+(-[a-zA-Z0-9]+)*\.)+[a-zA-Z]{2,}/[a-zA-Z0-9_\-]+/(/([a-zA-Z0-9_\-]+))*$
            example:
                GoMod: goa.design/model/examples/basic/model
            required:
                - GoMod
        UpsertComponentRequestBody:
            type: object
            properties:
                ContainerName:
                    type: string
                    description: Name of parent container
                    example: My Container
                Description:
                    type: string
                    description: Description of component
                    example: Component description
                Name:
                    type: string
                    description: Name of component
                    example: Component
                Properties:
                    type: object
                    description: Set of arbitrary name-value properties (shown in diagram tooltips)
                    example:
                        key1: value1
                        key2: value2
                    additionalProperties:
                        type: string
                        example: Consectetur exercitationem soluta quam quaerat quis.
                SystemName:
                    type: string
                    description: Name of parent software system
                    example: My System
                Tags:
                    type: array
                    items:
                        type: string
                        example: Dolores dolor.
                    description: Attached tags
                    example:
                        - Tag1
                        - Tag2
                Technology:
                    type: string
                    description: Technology used by component
                    example: Technology
                URL:
                    type: string
                    description: Documentation URL
                    example: https://component.com
            example:
                ContainerName: My Container
                Description: Component description
                Name: Component
                Properties:
                    key1: value1
                    key2: value2
                SystemName: My System
                Tags:
                    - Tag1
                    - Tag2
                Technology: Technology
                URL: https://component.com
            required:
                - SystemName
                - ContainerName
                - Name
        UpsertContainerRequestBody:
            type: object
            properties:
                Description:
                    type: string
                    description: Description of container
                    example: Container description
                Name:
                    type: string
                    description: Name of container
                    example: Container
                Properties:
                    type: object
                    description: Set of arbitrary name-value properties (shown in diagram tooltips)
                    example:
                        key1: value1
                        key2: value2
                    additionalProperties:
                        type: string
                        example: Occaecati est.
                SystemName:
                    type: string
                    description: Name of parent software system
                    example: My System
                Tags:
                    type: array
                    items:
                        type: string
                        example: Et vitae sapiente quisquam est ullam soluta.
                    description: Attached tags
                    example:
                        - Tag1
                        - Tag2
                Technology:
                    type: string
                    description: Technology used by container
                    example: Technology
                URL:
                    type: string
                    description: Documentation URL
                    example: https://container.com
            example:
                Description: Container description
                Name: Container
                Properties:
                    key1: value1
                    key2: value2
                SystemName: My System
                Tags:
                    - Tag1
                    - Tag2
                Technology: Technology
                URL: https://container.com
            required:
                - SystemName
                - Name
        UpsertRelationshipRequestBody:
            type: object
            properties:
                Description:
                    type: string
                    description: Description of relationship
                    example: Relationship description
                DestinationPath:
                    type: string
                    description: Path to destination element, see SourcePath for details.
                    example: Software System/Container/Component
                InteractionStyle:
                    type: string
                    description: Indicates whether the relationship is synchronous or asynchronous
                    default: Synchronous
                    example: Synchronous
                    enum:
                        - Synchronous
                        - Asynchronous
                SourcePath:
                    type: string
                    description: Path to source element consisting of <software system name>[/<container name>[/<component name>]]
                    example: Software System/Container/Component
                Tags:
                    type: array
                    items:
                        type: string
                        example: Dolores dolorum et ipsam veritatis perferendis.
                    description: Attached tags
                    example:
                        - Tag1
                        - Tag2
                Technology:
                    type: string
                    description: Technology used by relationship
                    example: Technology
                URL:
                    type: string
                    description: Documentation URL
                    example: https://relationship.com
                    format: uri
            example:
                Description: Relationship description
                DestinationPath: Software System/Container/Component
                InteractionStyle: Synchronous
                SourcePath: Software System/Container/Component
                Tags:
                    - Tag1
                    - Tag2
                Technology: Technology
                URL: https://relationship.com
            required:
                - SourcePath
                - DestinationPath
        UpsertSystemRequestBody:
            type: object
            properties:
                Description:
                    type: string
                    description: Description of system
                    example: System description
                Location:
                    type: string
                    description: Indicates whether the system is in-house (Internal) or hosted by a third party (External)
                    default: Internal
                    example: External
                    enum:
                        - Internal
                        - External
                Name:
                    type: string
                    description: Name of software system
                    example: System
                Properties:
                    type: object
                    description: Set of arbitrary name-value properties (shown in diagram tooltips)
                    example:
                        key1: value1
                        key2: value2
                    additionalProperties:
                        type: string
                        example: Quos aut.
                Tags:
                    type: array
                    items:
                        type: string
                        example: Expedita dolore nemo amet deserunt occaecati omnis.
                    description: Attached tags
                    example:
                        - Tag1
                        - Tag2
                URL:
                    type: string
                    description: Documentation URL
                    example: https://system.com
            example:
                Description: System description
                Location: Internal
                Name: System
                Properties:
                    key1: value1
                    key2: value2
                Tags:
                    - Tag1
                    - Tag2
                URL: https://system.com
            required:
                - Name
tags:
    - name: Editor
    - name: Module
    - name: Assets
